# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks-template.yml
    parameters:
      project name: "$(System.TeamProject)"
      repository name: "$(Build.Repository.Name)"
      branch name: "$(Build.SourceBranchName)"

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: tasks-template.yml
      
- job: MAC
  pool:
    vmImage: 'macos-latest'
  steps:
  - template: tasks-template.yml
  
