# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks-template.yml

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
# Run a PowerShell script on Linux, macOS, or Windows
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"
        Write-Host "$(System.TeamProject)"
        Write-Host "$(Build.Repository.Name)"
        Write-Host "$(Build.SourceBranchName)"
        Write-Host "$(Build.Reason)"
        Write-Host "$(Build.BuildId)"
        Write-Host "$(Build.ArtifactStagingDirectory)"
        Write-Host "$(Agent.BuildDirectory)"
        Write-Host "$(Agent.OS)"
        Write-Host "$(System.JobName)"
      
- job: MAC
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
# Run a PowerShell script on Linux, macOS, or Windows
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"
        Write-Host "$(System.TeamProject)"
        Write-Host "$(Build.Repository.Name)"
        Write-Host "$(Build.SourceBranchName)"
        Write-Host "$(Build.Reason)"
        Write-Host "$(Build.BuildId)"
        Write-Host "$(Build.ArtifactStagingDirectory)"
        Write-Host "$(Agent.BuildDirectory)"
        Write-Host "$(Agent.OS)"
        Write-Host "$(System.JobName)"
