# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks-template.yml
    parameters:
      param1: "$(System.TeamProject)"
      param2: "$(Build.Repository.Name)"
      param3: "$(Build.SourceBranchName)"

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: tasks-template.yml
    parameters:
      param1: "$(Build.Reason)"
      param2: "$(Build.BuildId)"
      param3: "$(Build.ArtifactStagingDirectory)"
      
- job: MAC
  pool:
    vmImage: 'macos-latest'
  steps:
  - template: tasks-template.yml
    parameters:
      param1: "$(Agent.BuildDirectory)"
      param2: "$(Agent.OS)"
      param3: "$(System.JobName)"
  
